create or alter table dim.d_employee 
(
	d_employee_id varchar not null,
	employee_id varchar,
	first_name varchar,
	last_name varchar,
	middle_name varchar,
	user_name varchar,
	email_address varchar,
	job_code varchar,
	job_title varchar,
	company_code varchar,
	company varchar,
	division_code varchar,
	division varchar,
	region_code varchar,
	region varchar,
	location_code varchar,
	location varchar,
	area varchar,
	status varchar,
	supervisor_employee_id varchar,
	supervisor_name varchar,
	create_date timestamp_ntz,
	created_by varchar,
	update_date timestamp_ntz,
	updated_by varchar,
	etl_created_date timestamp_ntz,
	etl_created_batch_id integer,
	etl_modified_date timestamp_ntz,
	etl_modified_batch_id integer,
	hashkey varchar,
	primary key (d_employee_id)
);